name: backend
services:
  api: 
    build: api
    env_file:
      - ./api/.env
    ports:
      - 5432:5432
  
  db:
    build: db
    env_file:
      - ../db/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    env_file:
      - .env

volumes:
  db_data: test